# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyZ22Kaz8yyRzyDm1luTbH3QI4nh6w6X
"""

import torch
import torch.nn as nn
from torchvision import models


class IMG2GPS(nn.Module):
    """
    ResNet18-based image-to-GPS regression model.

    Input:
        batch: Tensor of shape [B, 3, 224, 224]

    Output:
        Tensor of shape [B, 2], where columns are:
            [latitude_degrees, longitude_degrees]
    """

    def __init__(self):
        super().__init__()

        self.backbone = models.resnet18(weights=None)

        in_features = self.backbone.fc.in_features

        self.backbone.fc = nn.Sequential(
            nn.Linear(in_features, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 2)
        )

        self.register_buffer("lat_mean", torch.tensor(0.0))
        self.register_buffer("lat_std", torch.tensor(1.0))
        self.register_buffer("lon_mean", torch.tensor(0.0))
        self.register_buffer("lon_std", torch.tensor(1.0))

    def forward(self, batch):
        if isinstance(batch, (list, tuple)):
            batch = torch.stack(batch, dim=0)
        preds_norm = self.backbone(batch)

        lat = preds_norm[:, 0] * self.lat_std + self.lat_mean
        lon = preds_norm[:, 1] * self.lon_std + self.lon_mean

        return torch.stack([lat, lon], dim=1)

    def predict(self, batch):
        self.eval()
        with torch.no_grad():
            return self.forward(batch)


Model = IMG2GPS

def get_model():
    return IMG2GPS()